FROM node:alpine AS builder

RUN corepack enable
RUN corepack prepare pnpm@latest --activate

WORKDIR /app

COPY . .

RUN pnpm ci

RUN pnpm build

FROM nginx:latest AS production

COPY --from=builder /app/build /usr/share/nginx/html

COPY --from=builder /app/nginx.conf.rootless /etc/nginx/conf.d/default.conf

EXPOSE 8080

CMD [ "nginx", "-g", "daemon off;" ]