# Build the client libraries

FROM node:alpine AS libraries

RUN npm install -g pnpm

WORKDIR /app-lib

COPY ./belaberung-client-libs .

RUN pnpm ci

RUN pnpm build

# Build the website    

FROM node:alpine AS builder

RUN npm install -g pnpm

WORKDIR /app

COPY ./belaberung-webui .

COPY --from=libraries /app-lib ../belaberung-client-libs

RUN pnpm ci

RUN pnpm build

# Run it with nginx

FROM nginx:latest AS production

COPY --from=builder /app/build /usr/share/nginx/html

COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]