ARG BELABERUNG_DOMAIN

# Build the client libraries

FROM node:alpine AS libraries

RUN npm install -g pnpm

WORKDIR /app-lib

COPY ./belaberung-client-libs .

RUN pnpm ci

RUN pnpm build

# Build the website    

FROM node:alpine AS builder

RUN npm install -g pnpm

WORKDIR /app

COPY ./belaberung-webui .

COPY --from=libraries /app-lib ../belaberung-client-libs

RUN pnpm ci

RUN pnpm build

# Run it with nginx

FROM nginx:latest AS production

ARG BELABERUNG_DOMAIN

ENV BELABERUNG_DOMAIN=$BELABERUNG_DOMAIN

COPY --from=builder /app/build /usr/share/nginx/html

COPY --from=builder /app/nginx.conf /nginx.conf.template

EXPOSE 80

CMD ["/bin/sh" , "-c" , "envsubst '$BELABERUNG_WEBUI_PORT $BELABERUNG_WEBUI_BACKEND_HOST $BELABERUNG_WEBUI_SERVER_NAME $BELABERUNG_WEBUI_ROOT' < /nginx.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]