# Build a binary    

FROM golang:alpine AS builder

RUN apk update && apk add make

WORKDIR /app

COPY . .

ENV GIN_MODE=release

RUN make

# Run the built binary

FROM golang:alpine AS production

COPY --from=builder /app/bin/belaberung-server /go/belaberung-server

EXPOSE 8080

CMD [ "/go/belaberung-server" ]